# Generated by Django 5.1 on 2024-08-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciepe',
            name='reciepe_image',
            field=models.ImageField(upload_to='receipes'),
        ),
    ]
